session Posix = "HOL-Library" + 
theories[document = false]
     "HOL-Library.Sublist"
     "RegLangs"
     "PosixSpec"
     "Positions"
     "PDerivs"
     "Lexer"
     "LexerSimp"
     "Blexer"
     "BlexerSimp"
     "BasicIdentities"
     "ClosedForms"
     "GeneralRegexBound"
     "ClosedFormsBounds"
     "FBound"